#!/bin/bash
echo "-rwxrwxrwx 1 nyang nyang   31 Mar  7 16:41 '*\"Best School"\\*$?*****:'
drwxrwxrwx 1 nyang nyang  512 Mar  7 16:51  .
drwxrwxrwx 1 nyang nyang  512 Mar  7 12:33  ..
-rwxrwxrwx 1 nyang nyang   33 Mar  7 14:40  0-hello_world
-rwxrwxrwx 1 nyang nyang   24 Mar  7 14:32  1-confused_smiley
-rwxrwxrwx 1 nyang nyang 1654 Mar  7 14:49  2-hellofile
-rwxrwxrwx 1 nyang nyang 2104 Mar  7 15:04  3-twofiles
-rwxrwxrwx 1 nyang nyang  218 Mar  7 15:12  4-lastlines
-rwxrwxrwx 1 nyang nyang  441 Mar  7 15:18  5-firstlines
-rwxrwxrwx 1 nyang nyang   13 Mar  7 15:28  6-third_line
-rwxrwxrwx 1 nyang nyang   12 Mar  7 16:39  7-file
-rwxrwxrwx 1 nyang nyang   12 Mar  7 16:49  8-cwd_state
-rwxrwxrwx 1 nyang nyang   29 Mar  7 14:54  README.dm
-rwxrwxrwx 1 nyang nyang   12 Mar  7 16:51  ls_cwd_content"
